# Copyright (c) 2022 Softdel Systems Pvt. Ltd..
#

version: '3.6'

services:
  pid-controller:
      depends_on:
        - ia_eiibase
        - uwc_common
      build:
        context: $PWD/../uwc/pid/
        dockerfile: $PWD/../uwc/pid/Dockerfile
        args:
          UWC_VERSION: ${UWC_VERSION}
          EII_VERSION: ${EII_VERSION}
          EII_UID: ${EII_UID}
          EII_USER_NAME: ${EII_USER_NAME}
          BUILD_NUMBER: ${BUILD_NUMBER}
          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
          CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
      image: ghcr.io/uwc-control-app/pid-controller-1.0:latest
      container_name: pid-controller
      hostname: pid-controller
      read_only: true
      ulimits:
       rtprio:
         soft: "99" # these are the maximum values of priorites to be used inside the container application
         hard: "99"
      environment:
        AppName: "pid-controller"
        ETCD_HOST: ${ETCD_HOST}
        DEV_MODE: ${DEV_MODE}
        no_proxy: ${eii_no_proxy},${ETCD_HOST}
        ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
        ETCD_PREFIX: ${ETCD_PREFIX}
        Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
        MQTT_URL: "${MQTT_PROTOCOL}://mqtt_container:11883"
        PIDControllerConfigFile: "PID-controller-config.yml"
        # Clients: "TCP,RTU"
        BUILD_NUMBER: ${BUILD_NUMBER}
        PROFILING_MODE: ${PROFILING_MODE}
      logging:
          driver: "json-file"
          options:
              max-file: "3"
              max-size: "10m"
      user: ${EII_UID}
      networks:
        - eii
      volumes:
      - "${EII_INSTALL_PATH}/sockets:${SOCKET_DIR}:z"
      - "${EII_INSTALL_PATH}/uwc_data:/opt/intel/eii/uwc_data:ro"
      - "${EII_INSTALL_PATH}/uwc_data/common_config:${EII_INSTALL_PATH}/uwc_data/common_config:ro"
      - "${EII_INSTALL_PATH}/container_logs/pid-controller:/opt/intel/app/logs"
      - ./Certificates/pid-controller:/run/secrets/pid-controller
      - ./Certificates/rootca:/run/secrets/rootca
      - ./Certificates/mymqttcerts:/run/secrets/mymqttcerts    
      security_opt:
        - no-new-privileges
      healthcheck:
        test: ["CMD-SHELL", "/bin/sh","-c", "ps -C pid-controller >/dev/null && echo Running || echo Not running; exit 1"]
        interval: 60s
        timeout: 30s
        retries: 3
        start_period: 0s
