file:
  author: Control App Config utility
  date: 20/06/2022 15:59:17
  description: PID Controller Config File
app_configs:
  healthCheckTopicPre: pid-controller/health-check
  configurationTopicPre: pid-controller/config-params
  configPblshIntervalSec: 10
  extMqttBrokerIPAddr: 172.16.7.48
  extMqttPort: 1883
pid_configs:
- id: under-damped
  dGain: 1
  execIntervalMs: 10
  iGain: 0.004
  inputBounded: false
  inputLowerBound: 0.0
  inputUpperBound: 0.0
  loopEnabled: true
  outputBounded: false
  outputLowerBound: 10
  outputOnDisable: 20.0
  outputUpperBound: 100.0
  pGain: 2.1
  polledPoint: /dev1/gr1/D0
  setpoint: 60.0
  writePoint: /dev1/gr1/D1
- id: critically-damped
  dGain: 1
  execIntervalMs: 10
  iGain: 0.004
  inputBounded: false
  inputLowerBound: 0.0
  inputUpperBound: 0.0
  loopEnabled: true
  outputBounded: false
  outputLowerBound: 10
  outputOnDisable: 20.0
  outputUpperBound: 100.0
  pGain: 2.1
  polledPoint: /dev1/gr1/D2
  setpoint: 60.0
  writePoint: /dev1/gr1/D3
- id: over-damped
  dGain: 1
  execIntervalMs: 10
  iGain: 0.004
  inputBounded: false
  inputLowerBound: 0.0
  inputUpperBound: 0.0
  loopEnabled: true
  outputBounded: false
  outputLowerBound: 10
  outputOnDisable: 20.0
  outputUpperBound: 100
  pGain: 2.1
  polledPoint: /dev1/gr1/D4
  setpoint: 60.0
  writePoint: /dev1/gr1/D5
